export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Charts } from "./User/Charts";
export { default as Login } from "./Login";
export { default as DashboardPage } from "./User/DashboardPage";
export { default as ContactUs } from "./ContactUs";
export { default as TicketsViewer } from "./TicketsViewer";
export { default as CategoryManager } from "./CategoryManager";
export { default as UserTicketsManager } from "./User/UserTicketsManager";
