on:
  push:
    branches:
    - Develop
    - release/*
  workflow_dispatch:

jobs:
  build:
    name: Deploy on our vps
    runs-on: self-hosted
    env:
      NODE_ENV: production
      DATABASE_ACCESS: ${{ secrets.DATABASE_ACCESS }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_OAUTH_REDIRECT_URL: ${{ secrets.GOOGLE_OAUTH_REDIRECT_URL }}
      # Add other environment variables as needed

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: |
          cd backend
          npm ci
          node server.js
      
