name: Run Frontend Tests

on:
  push:
    branches: [master, main, Develop]
  pull_request:
    branches: [master, main, Develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      DATABASE_ACCESS: ${{ secrets.DATABASE_ACCESS }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_OAUTH_REDIRECT_URL: ${{ secrets.GOOGLE_OAUTH_REDIRECT_URL }}
      # Add other environment variables as needed

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Run API in Background
        working-directory: ./backend
        run: |
          npm ci
          npm run dev &
          echo $! > api_pid.txt

      - name: start frontend tests end-to-end
        working-directory: ./g-sonde
        run: |
          npm ci
          npm run test.e2e

      - name: start frontend unit tests
        working-directory: ./g-sonde
        run: |
          npm ci
          npm run test.unit

      - name: Stop API
        working-directory: ./backend
        run: |
          kill -9 $(cat ../g-sonde/api_pid.txt)
