name: Run tests

on:
    push:
        branches: [master, main, Develop]
    pull_request:
        branches: [master, main, Develop]
    workflow_dispatch:

jobs:
    backend-tests:
        runs-on: ubuntu-latest
        env:
            NODE_ENV: test
            DATABASE_ACCESS: ${{ secrets.DATABASE_ACCESS }}
            ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
            REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
            GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            GOOGLE_OAUTH_REDIRECT_URL: ${{ secrets.GOOGLE_OAUTH_REDIRECT_URL }}
            # Add other environment variables as needed

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - name: start server and test it
              run: |
                  cd backend
                  npm ci
                  npm test

    frontend-tests:
        needs: backend-tests
        runs-on: ubuntu-latest
        env:
            VITE_URL_API: ${{ secrets.VITE_URL_API }}
            RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - name: Install dependencies and build
              run: |
                  cd g-sonde
                  npm ci
                  npm run build
            - name: Install dependencies and launch tests
              run: |
                  cd g-sonde
                  npm ci
                  npm run test.unit
                  npm run test.e2e
